package frontend;

import com.csc.OrderWriter;
import com.csc.SqlDatabase;
import com.csc.TransportWriter;
import com.csc.model.Parcel;
import com.csc.model.Vehicle;

import java.awt.Color;
import java.awt.Component;
import java.sql.SQLData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author ssb7848
 */
public class Inventory extends javax.swing.JFrame {

  private SqlDatabase db;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAddParcel;
  private javax.swing.JButton btnAddVehicle;
  private javax.swing.JButton btnExit;
  private javax.swing.JButton btnModify;
  private javax.swing.JButton btnRemoveOrder;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lblSearch;
  private javax.swing.JTable tblParcel;
  private javax.swing.JTable tblVehicles;
  private javax.swing.JTextField tbxSearch;
  /**
   * Creates new form Inventory
   */
  public Inventory(SqlDatabase db) {
    this.db = db;
    initComponents();
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[], SqlDatabase db) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | javax.swing.UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
      java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Inventory(db).setVisible(true));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblParcel = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    tbxSearch = new javax.swing.JTextField();
    btnUpdate = new javax.swing.JButton();
    btnRemoveOrder = new javax.swing.JButton();
    lblSearch = new javax.swing.JLabel();
    btnModify = new javax.swing.JButton();
    btnExit = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tblVehicles = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    btnAddVehicle = new javax.swing.JButton();
    btnAddParcel = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(204, 255, 204));

    jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    tblParcel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    tblParcel.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String[] {
            "Parcel Id", "Weight", "Size", "Price", "Zip"
        }
    ));
    jScrollPane1.setViewportView(tblParcel);

    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel2.setText("Inventory Edit");
    jLabel2.setToolTipText("");

    tbxSearch.addActionListener(this::tbxSearchActionPerformed);

    btnUpdate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    btnUpdate.setText("Update");
    btnUpdate.addActionListener(this::btnUpdateActionPerformed);

    btnRemoveOrder.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    btnRemoveOrder.setText("remove Customer");
    btnRemoveOrder.addActionListener(this::btnRemoveOrderActionPerformed);

    lblSearch.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblSearch.setText("Search");

    btnModify.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    btnModify.setText("Modify");
    btnModify.addActionListener(this::btnModifyActionPerformed);

/*    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnRemoveOrder)
                            .addComponent(btnModify))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 200, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addGap(18, 18, 18)
                                .addComponent(tbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(68, 68, 68))))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveOrder)
                .addGap(18, 18, 18)
                .addComponent(btnModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addContainerGap(34, Short.MAX_VALUE))
    );*/

    btnExit.setText("Exit");
    btnExit.addActionListener(this::btnExitActionPerformed);

    tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null}
        },
        new String[] {
            "Vehicle Id", "Vehicle Type", "Milage"
        }
    ));
    jScrollPane2.setViewportView(tblVehicles);

    jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
    jLabel1.setText("Inventory Menu");

    jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    btnAddVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Falcon-icon.png"))); // NOI18N
    btnAddVehicle.addActionListener(this::btnAddVehicleActionPerformed);

/*    btnAddParcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add Inventory-icon.png"))); // NOI18N
    btnAddParcel.addActionListener(this::btnAddParcelActionPerformed);*/

    jLabel3.setText("Add Vehicle");

//    jLabel4.setText("Add Parcel");

    btnAddParcel.setVisible(false);
    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddParcel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddParcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 40, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
    );

    updateParcelModel();
    updateVehicleModel();
    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void updateParcelModel() {
    OrderWriter writer = new OrderWriter(db);
    List<Parcel> parcels = new ArrayList<>();

    try {
      parcels = writer.allParcels();
    } catch (Exception e) {
      e.printStackTrace();
    }

    Object[][] arr = new Object[parcels.size()][];

    for (int i = 0; i < arr.length; i++) {
      arr[i] = parcelsToArray(parcels.get(i));
    }

    tblParcel.setModel(new DefaultTableModel(arr, new String[] {"Parcel ID", "Weight", "Size", "Price"}));
  }

  private Object[] parcelsToArray(Parcel p) {
    return new Object[] { p.getPid(), p.getWeight(), p.getSize(), p.getPrice() };
  }

  public void updateVehicleModel() {
    TransportWriter writer = new TransportWriter(db);
    List<Vehicle> vehicles = new ArrayList<>();

    try {
      vehicles = writer.getAllVehicles();
    } catch (Exception e) {
      e.printStackTrace();
    }

    Object[][] arr = new Object[vehicles.size()][];

    for (int i = 0; i < arr.length; i++) {
      arr[i] = vehicleToArray(vehicles.get(i));
    }

    tblVehicles.setModel(new DefaultTableModel(arr, new String[] {"Vehicle ID", "Type",
        "Mileage"}));

  }

  private Object[] vehicleToArray(Vehicle vehicle) {
    return new Object[]{ vehicle.getVid(), vehicle.getType(), vehicle.getMileage() };
  }

  private void tbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxSearchActionPerformed
    // TODO add your handling code here:
    String value = tbxSearch.getText();

    for (int row = 0; row <= tblParcel.getRowCount() - 1; row++) {

      for (int col = 0; col <= tblParcel.getColumnCount() - 1; col++) {

        if (value.equals(tblParcel.getValueAt(row, col))) {

          // this will automatically set the view of the scroll in the location of the value
          tblParcel.scrollRectToVisible(tblParcel.getCellRect(row, 0, true));

          // this will automatically set the focus of the searched/selected row/value
          tblParcel.setRowSelectionInterval(row, row);

          for (int i = 0; i <= tblParcel.getColumnCount() - 1; i++) {

            tblParcel.getColumnModel().getColumn(i).setCellRenderer(new HighlightRenderer());
          }
        }
      }
    }
  }//GEN-LAST:event_tbxSearchActionPerformed

  private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    // TODO add your handling code here:
    tblParcel.setEnabled(false
    );
  }//GEN-LAST:event_btnUpdateActionPerformed

  private void btnRemoveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderActionPerformed
    // TODO add your handling code here:
    DefaultTableModel model1 = (DefaultTableModel) tblParcel.getModel();
    try {
      int SelectedRowIndex = tblParcel.getSelectedRow();
      model1.removeRow(SelectedRowIndex);

    } catch (Exception ex) {
      JOptionPane.showMessageDialog(null, ex);
    }
  }//GEN-LAST:event_btnRemoveOrderActionPerformed

  private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
    // TODO add your handling code here:
    tblParcel.setEnabled(rootPaneCheckingEnabled);
    tblParcel.isEditing();
  }//GEN-LAST:event_btnModifyActionPerformed

  private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    // TODO add your handling code here:

    dispose();
  }//GEN-LAST:event_btnExitActionPerformed

  private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
    // TODO add your handling code here:
    AddVehicleForm form = new AddVehicleForm(this, db);
    form.setVisible(true);

  }//GEN-LAST:event_btnAddVehicleActionPerformed

  private void btnAddParcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParcelActionPerformed
    // TODO add your handling code here:

    DefaultTableModel model1 = (DefaultTableModel) tblParcel.getModel();
    tblParcel = new JTable(model1);
    model1.addRow(new Object[] {"", "", "", "", ""});

  }//GEN-LAST:event_btnAddParcelActionPerformed

  private class HighlightRenderer extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

      // everything as usual
      super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

      // added behavior
      if (row == table.getSelectedRow()) {

        // this will customize that kind of border that will be use to highlight a row
        setBorder(BorderFactory.createMatteBorder(2, 1, 2, 1, Color.BLACK));
      }

      return this;
    }
  }
  // End of variables declaration//GEN-END:variables
}
