package frontend;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.csc.Authentication;
import com.csc.EmployeeRoleReader;
import com.csc.SqlDatabase;
import com.csc.model.Customer;
import com.csc.model.Employee;
import com.csc.model.EmployeeRole;
import csc455.SqlConfig;

import javax.swing.*;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.Collectors;

/**
 * @author schoolStuff
 */
public class LoginScreen extends javax.swing.JFrame {

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JPanel btnSignIn;
  private JButton jButton1;
  private JButton jButton2;
  private JLabel jLabel1;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JLabel jLabel4;
  private JLabel jLabel5;
  private JPasswordField txfPassword;
  private JTextField txfUserName;

  private SqlDatabase db;

  /**
   * Creates new form LoginScreen
   */
  public LoginScreen() throws SQLException {
    initComponents();
    db = new SqlDatabase(SqlConfig.MY_SQL_URL, SqlConfig.MY_SQL_DB, SqlConfig.MY_SQL_USER,
        SqlConfig.MY_SQL_PS);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      try {
        new LoginScreen().setVisible(true);
      } catch (SQLException e) {
        e.printStackTrace();
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new JLabel();
    btnSignIn = new JPanel();
    jButton2 = new JButton();
    txfUserName = new javax.swing.JTextField();
    txfPassword = new javax.swing.JPasswordField();
    jLabel2 = new JLabel();
    jLabel3 = new JLabel();
    jLabel5 = new JLabel();
    jButton1 = new JButton();
    jLabel4 = new JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
    jLabel1.setText("Welcome to SmartUShip");

    btnSignIn.setBackground(new java.awt.Color(204, 255, 204));
    btnSignIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jButton2.setText("Sign In");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    txfUserName.addActionListener(this::txfUserNameActionPerformed);

    jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel2.setText("Password");

    jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel3.setText("UserName");

    javax.swing.GroupLayout btnSignInLayout = new javax.swing.GroupLayout(btnSignIn);
    btnSignIn.setLayout(btnSignInLayout);
    btnSignInLayout.setHorizontalGroup(
        btnSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSignInLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(btnSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txfUserName))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSignInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(36, 36, 36))
    );

    btnSignInLayout.setVerticalGroup(
        btnSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSignInLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(btnSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(btnSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(38, 38, 38))
    );

    jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
    jLabel5.setText("New Customer Please Sign Up");

    jButton1.setBackground(new java.awt.Color(255, 204, 51));
    jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

    ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("customer-icon.png"));

    jButton1.setIcon(icon);
    jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel4.setText("Sign Up");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Authentication auth = new Authentication(db);
    Object result = auth.logIn(txfUserName.getText(), new String(txfPassword.getPassword()));

    if (result instanceof Customer) {
      CustomerLandingPage.main(null, db, (Customer) result);
      this.setVisible(false);
    } else if (result instanceof Employee) {
      try {
        List<EmployeeRole> roles = (new EmployeeRoleReader(db)).readRoles();

        List<EmployeeRole> stream = roles.stream()
            .filter(e -> ((Employee)result).getRoleid() == e.getRid())
            .collect(Collectors.toList());


        if (stream.get(0).getDescription().equalsIgnoreCase("Admin")) {
          Management.main(null, db, (Employee) result);
          this.setVisible(false);
        } else {
          EmployeeWindow.main(null, db, (Employee) result);
          this.setVisible(false);
        }
      } catch (SQLException e) {
        e.printStackTrace();
      }
    }

  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    SignUps.main(null, db);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void txfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUserNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txfUserNameActionPerformed
  // End of variables declaration//GEN-END:variables
}
