package frontend;

import com.csc.EmployeeWriter;
import com.csc.SqlDatabase;
import com.csc.model.Employee;
import com.csc.model.Vehicle;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author ssb7848
 */
public class ManageEmployee extends javax.swing.JFrame {

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAddParcel;
  private javax.swing.JButton btnExit;
  private javax.swing.JButton btnModify;
  private javax.swing.JButton btnRemoveEmployee;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblSearch;
  private javax.swing.JTable tblEmployee;
  private javax.swing.JTextField tbxSearch;

  private SqlDatabase db;

  /**
   * Creates new form ManageEmployee
   */
  public ManageEmployee(SqlDatabase db) {
    this.db = db;
    initComponents();

  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[], SqlDatabase db) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | javax.swing.UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
      java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new ManageEmployee(db).setVisible(true));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblEmployee = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    tbxSearch = new javax.swing.JTextField();
    btnUpdate = new javax.swing.JButton();
    btnUpdate.setVisible(false);
    btnRemoveEmployee = new javax.swing.JButton();
    lblSearch = new javax.swing.JLabel();
    btnModify = new javax.swing.JButton();
    btnModify.setVisible(false);
    btnAddParcel = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    btnExit = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    tblEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String[] {
            "EmployeeWindow Id", "E_Last Name", "E_Name", "User Id", "Role", "Title 6", "Vehicle Type"
        }
    ));
    jScrollPane1.setViewportView(tblEmployee);

    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel2.setText("EmployeeWindow Edit");
    jLabel2.setToolTipText("");

    tbxSearch.addActionListener(this::tbxSearchActionPerformed);

    btnUpdate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    btnUpdate.setText("Update");
    btnUpdate.addActionListener(this::btnUpdateActionPerformed);

    btnRemoveEmployee.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    btnRemoveEmployee.setText("remove EmployeeWindow");
    btnRemoveEmployee.addActionListener(this::btnRemoveEmployeeActionPerformed);

    lblSearch.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    lblSearch.setText("Search");

    btnModify.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    btnModify.setText("Modify");
    btnModify.addActionListener(this::btnModifyActionPerformed);

    btnAddParcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee-icon.png"))); // NOI18N
    btnAddParcel.addActionListener(this::btnAddParcelActionPerformed);

    jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel3.setText("Add EmployeeWindow");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnRemoveEmployee)
                            .addComponent(btnModify))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(btnAddParcel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(tbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(69, 69, 69))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveEmployee)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddParcel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addContainerGap())
    );

    jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
    jLabel1.setText("EmployeeWindow Menu");

    btnExit.setText("Exit");
    btnExit.addActionListener(this::btnExitActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
    );

    updateTable();
    pack();
  }

  private void tbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxSearchActionPerformed
    // TODO add your handling code here:
    String value = tbxSearch.getText();

    for (int row = 0; row <= tblEmployee.getRowCount() - 1; row++) {

      for (int col = 0; col <= tblEmployee.getColumnCount() - 1; col++) {

        if (value.equals(tblEmployee.getValueAt(row, col))) {

          // this will automatically set the view of the scroll in the location of the value
          tblEmployee.scrollRectToVisible(tblEmployee.getCellRect(row, 0, true));

          // this will automatically set the focus of the searched/selected row/value
          tblEmployee.setRowSelectionInterval(row, row);

          for (int i = 0; i <= tblEmployee.getColumnCount() - 1; i++) {

            tblEmployee.getColumnModel().getColumn(i).setCellRenderer(new HighlightRenderer());
          }
        }
      }
    }
  }//GEN-LAST:event_tbxSearchActionPerformed

  private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    // TODO add your handling code here:
    tblEmployee.setEnabled(false
    );
  }//GEN-LAST:event_btnUpdateActionPerformed

  private void btnRemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEmployeeActionPerformed
    // TODO add your handling code here:
    EmployeeWriter writer = new EmployeeWriter(db);

    try {
      writer.deleteUser((Integer) tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 4));
      updateTable();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
    // TODO add your handling code here:
    tblEmployee.setEnabled(rootPaneCheckingEnabled);
    tblEmployee.isEditing();
  }//GEN-LAST:event_btnModifyActionPerformed

  private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    // TODO add your handling code here:
    dispose();
  }//GEN-LAST:event_btnExitActionPerformed

  private void btnAddParcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParcelActionPerformed
    // TODO add your handling code here:
    AddEmployeeForm form = new AddEmployeeForm(this, db);
    form.setVisible(true);
  }//GEN-LAST:event_btnAddParcelActionPerformed

  private class HighlightRenderer extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

      // everything as usual
      super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

      // added behavior
      if (row == table.getSelectedRow()) {

        // this will customize that kind of border that will be use to highlight a row
        setBorder(BorderFactory.createMatteBorder(2, 1, 2, 1, Color.BLACK));
      }

      return this;
    }
  }

  public void updateTable() {
    EmployeeWriter writer = new EmployeeWriter(db);
    List<Employee> emps = new ArrayList<>();

    try {
      emps = writer.getAllEmployees();
    } catch (Exception e) {
      e.printStackTrace();
    }

    Object[][] empsArr = new Object[emps.size()][];
    for (int i = 0; i < empsArr.length; i++) {
      empsArr[i] = empToArr(emps.get(i));
    }

    tblEmployee.setModel(new DefaultTableModel(empsArr, new String[]{"EmployeeWindow Id", "E_Last Name", "E_Name", "Email", "User Id", "Vehicle Type"}));
  }

  private Object[] empToArr(Employee emp) {
    return new Object[] { emp.getEid(), emp.getLastName(), emp.getFirstName(), emp.getEmail(), emp.getUid(), emp.getVehicleType(),};
  }
  // End of variables declaration//GEN-END:variables
}
